[project]
name = "pysteroids"
version = "0.1.0"
description = "Asteroid game project using Python for Boot.dev course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
